/**
 * Auto-generated from src/config/anime-subreddits.yaml
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run: pnpm generate:anime
 */

export interface AnimeMapping {
  title: string;
  subreddits: string[];
  aliases: string[];
  season_specific: boolean;
}

export const ANIME_MAPPINGS: AnimeMapping[] = [
  {
    "title": "One Piece",
    "subreddits": [
      "OnePiece"
    ],
    "aliases": [
      "One Piece",
      "OP"
    ],
    "season_specific": false
  },
  {
    "title": "Jujutsu Kaisen",
    "subreddits": [
      "JujutsuKaisen"
    ],
    "aliases": [
      "JJK",
      "Jujutsu"
    ],
    "season_specific": false
  },
  {
    "title": "Attack on Titan",
    "subreddits": [
      "attackontitan"
    ],
    "aliases": [
      "AOT",
      "Shingeki no Kyojin",
      "SnK"
    ],
    "season_specific": false
  },
  {
    "title": "My Hero Academia",
    "subreddits": [
      "MyHeroAcademia",
      "BokuNoHeroAcademia"
    ],
    "aliases": [
      "MHA",
      "BNHA",
      "My Hero"
    ],
    "season_specific": false
  },
  {
    "title": "Demon Slayer",
    "subreddits": [
      "KimetsuNoYaiba"
    ],
    "aliases": [
      "Kimetsu no Yaiba",
      "KnY"
    ],
    "season_specific": false
  },
  {
    "title": "Chainsaw Man",
    "subreddits": [
      "ChainsawMan"
    ],
    "aliases": [
      "CSM"
    ],
    "season_specific": false
  },
  {
    "title": "The Beginning After the End",
    "subreddits": [
      "tbate"
    ],
    "aliases": [
      "TBATE"
    ],
    "season_specific": false
  },
  {
    "title": "Spy x Family",
    "subreddits": [
      "SpyxFamily"
    ],
    "aliases": [
      "SpyFamily",
      "Spy Family"
    ],
    "season_specific": false
  },
  {
    "title": "Tower of God",
    "subreddits": [
      "TowerOfGod"
    ],
    "aliases": [
      "ToG"
    ],
    "season_specific": false
  },
  {
    "title": "Solo Leveling",
    "subreddits": [
      "SoloLeveling"
    ],
    "aliases": [
      "Sung Jinwoo"
    ],
    "season_specific": false
  }
];

/**
 * Find anime mapping by title (with fuzzy matching support for aliases)
 * @param title Anime title to search for
 * @returns AnimeMapping if found, null otherwise
 */
export function findAnimeMapping(title: string): AnimeMapping | null {
  if (!title) return null;

  const normalizedInput = title.toLowerCase().trim();

  // Exact match on title first
  let found = ANIME_MAPPINGS.find((a) => a.title.toLowerCase() === normalizedInput);
  if (found) return found;

  // Check aliases
  found = ANIME_MAPPINGS.find((a) =>
    a.aliases.some((alias) => alias.toLowerCase() === normalizedInput),
  );
  if (found) return found;

  // Partial match on title (contains)
  found = ANIME_MAPPINGS.find((a) => a.title.toLowerCase().includes(normalizedInput));
  if (found) return found;

  // Partial match on aliases
  found = ANIME_MAPPINGS.find((a) =>
    a.aliases.some((alias) => alias.toLowerCase().includes(normalizedInput)),
  );

  return found || null;
}

/**
 * Get subreddit list for an anime (with fallback)
 * @param title Anime title
 * @returns Array of subreddit names to search
 */
export function getSubredditsForAnime(title: string): string[] {
  const mapping = findAnimeMapping(title);
  return mapping?.subreddits || [];
}
